global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'python_app'
    static_configs:
      - targets: ['python_app:8000']

  - job_name: 'custom_exporter'
    metrics_path: /custom-metrics
    static_configs:
      - targets: ['custom_exporter:8001']
